#! /bin/bash
# Build lzz.  Produces build/lzz (dynamic, system libs only) and
# build/lzz-static (fully static, zero dependencies) in the repo, then runs
# the probe suite against the static binary.
#
# Environment overrides:
#   LZZ        bootstrap lzz binary       (default: the frozen binary in
#              /z6pool/z/dev/lzz/bin.OLD, so builds are deterministic and
#              independent of whatever lzz is installed; falls back to an
#              installed lzz for clones outside this project tree)
#   BUILDROOT  scratch build directory    (default: /tmp/lzz-build-$USER)
#
# The scratch directory must be on LOCAL disk: building inside an NFS tree
# intermittently produces empty object files (see test/README).  The build is
# always from clean, which is mandatory after parser-table regeneration and
# cheap enough to do every time.
set -e

REPO=$(cd "$(dirname "$0")/.." && pwd)

if [ -z "$LZZ" ]; then
    for c in "$(command -v lzz || true)" /usr/local/bin/lzz "$REPO/bin/lzz-$(uname -m)" /z6pool/z/dev/lzz/bin.OLD/lzz.OLD; do
        if [ -n "$c" ] && [ -x "$c" ]; then
            LZZ=$c
            break
        fi
    done
fi
[ -n "$LZZ" ] && "$LZZ" -v >/dev/null 2>&1 || { echo "no usable bootstrap lzz found (set LZZ=...)" >&2; exit 1; }

BUILDROOT=${BUILDROOT:-/tmp/lzz-build-$USER}

export PRJDIR=$REPO
export CONFIG=gcc.opt
export CONFIGDIR=$BUILDROOT/gcc.opt
export OBJDIR=$CONFIGDIR/objs
export LZZ

echo "== lzz build: bootstrap=$LZZ scratch=$CONFIGDIR"
rm -rf "$CONFIGDIR"
mkdir -p "$CONFIGDIR/gencode" "$CONFIGDIR/objs" "$CONFIGDIR/libs"

# generate all code first: the per-directory loop compiles each subdir right
# after generating it, but sources include headers generated by later subdirs
make -C "$REPO" -f Makefile.build gencode
make -C "$REPO" -f Makefile.build

# link both flavors
make -C "$REPO/main" programs BUILD_LZZ="$BUILDROOT/lzz"
make -C "$REPO/main" programs BUILD_LZZ="$BUILDROOT/lzz-static" LINKOPTIONS=-static

mkdir -p "$REPO/build"
cp "$BUILDROOT/lzz" "$BUILDROOT/lzz-static" "$REPO/build/"

echo "== probe suite (static binary)"
"$REPO/test/run_probes.sh" "$REPO/build/lzz-static"

# the deliverable: the static binary, named for this machine's architecture,
# next to the bin/lzz dispatcher (bin/ is never cleaned)
cp "$BUILDROOT/lzz-static" "$REPO/bin/lzz-$(uname -m)"

echo "== built:"
ls -la "$REPO/build/lzz" "$REPO/build/lzz-static" "$REPO/bin/lzz-$(uname -m)"
